version: '3.7'



services:
  postgres:
    container_name: postgres_db
    image: postgres
    networks:
      - passkeys_network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
     - 5432:5432
    restart: always
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - passkeys_network
    restart: unless-stopped
    depends_on:
      - postgres



networks:
  passkeys_network:
volumes:
  pgdata:
  pgadmin:
